language: node_js
node_js:
- 10.15.3
cache:
  apt: true
  yarn: true
  directories:
  - node_modules
before_install:
- export TZ='Asia/Beijing'  # 设置时区
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config user.name 'LbhFront-end'
- git config user.email '544289495@qq.com'
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
after_script:
- git clone https://${GH_REF} .deploy_git
- cd .deploy_git
- git checkout master
- cd ../
- mv .deploy_git/.git/ ./public/
- cd ./public
- git config user.name "LbhFront-end"
- git config user.email "544289495@qq.com"
- git add .
- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
- git push --force --quiet "https://${blog}@${GH_REF}" master:master
branches:
  only:
  - dev
env:
  global:
  - GH_REF: github.com/LbhFront-end/LbhFront-end.github.io.git
notifications:
  email:
  - 544289495@qq.com
  on_success: change
  on_failure: always
